[INTERFACE]
#Set to valid path if dedicated log file is needed
log_file = None
log_level = INFO
languages = LAT,ENG,RUS
default_language_index = 0
# Folder for images & sounds
assets_loader = assets
#List of images used in the interface
images = red_button.png,red_button_50.png
bg_image = EGL_background.png
font = DejaVu Sans Mono,50
button_debounce_time_ms = 1000
# Time in milliseconds to activate default button after last press
button_reset_to_default_time_ms = 10000  
#Settings for display brightness 0 - 255
screen_brightness_active = 255
screen_brightness_normal = 100
screen_brightness_inactive = 50

[BARCODE]
bc_reader_port = /dev/ttyACM0
#Barcode reader timeout in secs
bc_timeout=.5
#Regex to validate barcode
bc_regex = ^\d{7,9}#\d{4,5}

[REPORT]
host = 10.100.50.104
#HTTP request connection timeout
httpreq_timeout = 10
#Seconds to wait for report printout 
report_delay=7
#url template for CURL request
url=http://{}/csp/sarmite/ea.kiosk.pdf.cls?HASH={}&LANG={}
#url for testing host response 
url_test=http://10.100.50.102/sarmite/m5menu.csp
#Printers make and PPD for auto selection, seperated by comma in dict {'HP':'HP_PPD','Canon':Canon_PPD'}
printers={"HP": "HP LaserJet Series PCL 6 CUPS","Kyocera": "ECOSYS P3260dn, driverless, cups-filters 1.28.17"}
#Button to activate printer reset at startup
button_printer_reset=1

[WATCHDOG]
#Watchdog device, Comment to disable
watchdog_device=/dev/watchdog
